# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dgarizad <dgarizad@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/04/07 19:16:57 by dgarizad          #+#    #+#              #
#    Updated: 2023/04/07 21:50:48 by dgarizad         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = fractol
SRC = $(wildcard *.c)
HEADER = ./inc/fractal.h
MINILIBX = ./minilibx/libmlx.a

OBJS = $(SRC:.c=.o)
CC = gcc -g
CFLAGS = -Wall -Wextra -Werror
  
all: $(NAME)

%.o: %.c
	@$(CC) -c $< -o $@ $(CFLAGS) -Imlx

$(NAME): $(OBJS) $(HEADER) $(MINILIBX)
	@$(CC) $(OBJS) $(MINILIBX) -framework OpenGL -framework AppKit -o $(NAME) $(CFLAGS) 

$(MINILIBX): 
	make -C ./minilibx
	
clean :
	rm  -f *.o
fclean: clean
		rm -f $(NAME)
		make -C ./minilibx
re: fclean all
.PHONY : all clean fclean re 
